{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "appstack.fullname" . }}
  labels:
    {{- include "appstack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "appstack.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}